/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface JellyCheckbox {
    /**
    * checked property that can be used to get/set the value. Accepts only boolean valuess
    */
    'checked': boolean;
    /**
    * disabled property that can be used to get/set the value. Accepts only boolean values
    */
    'disabled': boolean;
    /**
    * Indeterminate state & property of checkbox
    */
    'indeterminate': boolean;
    /**
    * label attribute that can be used to set the label text
    */
    'label': string;
  }
  interface JellyCheckboxAttributes extends StencilHTMLAttributes {
    /**
    * checked property that can be used to get/set the value. Accepts only boolean valuess
    */
    'checked'?: boolean;
    /**
    * disabled property that can be used to get/set the value. Accepts only boolean values
    */
    'disabled'?: boolean;
    /**
    * Indeterminate state & property of checkbox
    */
    'indeterminate'?: boolean;
    /**
    * label attribute that can be used to set the label text
    */
    'label'?: string;
    /**
    * This is an event that is emitted when the state of the box is changed
    */
    'onChange'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'JellyCheckbox': Components.JellyCheckbox;
  }

  interface StencilIntrinsicElements {
    'jelly-checkbox': Components.JellyCheckboxAttributes;
  }


  interface HTMLJellyCheckboxElement extends Components.JellyCheckbox, HTMLStencilElement {}
  var HTMLJellyCheckboxElement: {
    prototype: HTMLJellyCheckboxElement;
    new (): HTMLJellyCheckboxElement;
  };

  interface HTMLElementTagNameMap {
    'jelly-checkbox': HTMLJellyCheckboxElement
  }

  interface ElementTagNameMap {
    'jelly-checkbox': HTMLJellyCheckboxElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
